### ISSUE TITLE
build.py fails badly when untracked files are in the working directory

### ISSUE THREAD

**Issue by coriolinus** [coriolinus/train_whistle#2]
When an untracked file is present in the build directory, the build fails in an unpleasant way, requiring manual entry of the command `git stash pop` to recover your working directory. Example:

``` PowerShell
D:\Users\coriolinus\Documents\Projects\train_whistle [master +0 ~1 -0]> python .\build.py
Saved working directory and index state WIP on master: 31ab209 Finish work on `build.py` for now.
HEAD is now at 31ab209 Finish work on `build.py` for now.
Traceback (most recent call last):
  File ".\build.py", line 198, in <module>
    stashed = stash()
  File ".\build.py", line 46, in stash
    assert git_is_clean()
AssertionError
D:\Users\coriolinus\Documents\Projects\train_whistle [master +1 ~0 -0 !]> git stash pop
On branch master
Your branch is ahead of 'origin/master' by 5 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   control.lua

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        foo.txt

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (aa92a1a4158635ece0ee882824a27eb1f18b5ba6)
```
# Workaround

Simply ensure all files in the working directory are tracked or in .gitignore. However, the point is to make this a development-friendly tool, so we'll need to handle that case sooner or later.

**Comment by coriolinus** [comment]
The most likely solution is to add some code in `git_is_clean` to actually parse the results from `git status` and ignore lines beginning with '??'. It's just a bit of a pain to handle right now.
